# Generated by Django 4.2.15 on 2025-05-16 18:57

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0002_attendance_scan_in_time_attendance_scan_out_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salarycalculations',
            options={'ordering': ['-month_year', 'employee__name']},
        ),
        migrations.RenameField(
            model_name='salarycalculations',
            old_name='month',
            new_name='month_year',
        ),
        migrations.AddField(
            model_name='salarycalculations',
            name='basic_salary_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='salarycalculations',
            name='generated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='salarycalculations',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='salarycalculations',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salarycalculations',
            name='overtime_rate_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='salarycalculations',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salarycalculations',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salarycalculations',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed to Generate')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='salarycalculations',
            name='total_bonuses_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='salarycalculations',
            name='total_deductions_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='salarycalculations',
            name='total_hours_worked',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='salarycalculations',
            name='total_overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='shift',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Night', 'Night'), ('Absent', 'Absent')], max_length=10),
        ),
        migrations.AlterField(
            model_name='salarycalculations',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterUniqueTogether(
            name='salarycalculations',
            unique_together={('employee', 'month_year')},
        ),
        migrations.RemoveField(
            model_name='salarycalculations',
            name='overtime_hours',
        ),
        migrations.RemoveField(
            model_name='salarycalculations',
            name='total_bonuses',
        ),
        migrations.RemoveField(
            model_name='salarycalculations',
            name='total_deductions',
        ),
        migrations.RemoveField(
            model_name='salarycalculations',
            name='total_hours',
        ),
    ]
